version:  '3.9'
services:
  product-service:
    image:  product_image
    container_name: product-service
    build:  UserProduct/
    restart:  always
    network_mode: user-network
    ports:
      - 8081:8081
    depends_on:
      - mongoService
      - apigateway

  mongoService:
    image:  mongo
    container_name: mongoService
    ports:
      - 27017:27017
    network_mode: user-network

  authenticationService:
    image:  authentication_image
    container_name: authenticationService
    build:  UserAuthentication/
    restart:  always
    network_mode: user-network
    ports:
      - 8091:8091
    depends_on:
      - mysqlService
      - apigateway

  mysqlService:
    image:  mysql:latest
    container_name: mysqlService
    network_mode: user-network
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  apigateway:
    container_name: apigateway
    build: demoapigateway/
    network_mode: user-network
    ports:
      - 9010:9010